apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "application.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  strategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
  selector:
    matchLabels:
      app: {{ template "application.name" . }}
  template:
    metadata:
      labels:
        name: {{ template "application.name" . }}
        app: {{ template "application.name" . }}
        chart: {{ template "application.chart" . }}
    spec:
      containers:
      - name: {{ template "application.name" . }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repo }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        {{- range $item:= .Values.service.ports }}
          - containerPort: {{ $item.containerPort }}
            name: {{ $item.name }}
            protocol: {{ $item.protocol }}
        {{- end }}
        env:
          - name: SERVICE_PORT
            value: "{{ (index .Values.service.ports 0).containerPort }}"
        args:
          - "/opt/tk_sasidaemon_starter/tk_sasidaemon_starter"

        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        livenessProbe:
{{ toYaml .Values.livenessProbe| indent 10 }}
        volumeMounts:
        - name: {{ (index .Values.volumes 0).name }}
          mountPath: {{ (index .Values.volumeMounts 0).path }}
      volumes:
      - name: {{ (index .Values.volumes 0).name }}
        configMap:
          name: {{ template "application.name" . }}