{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "application.name" . }}
  labels:
    name: {{ template "application.name" . }}
    chart: {{ template "application.chart" . }}
    release: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "application.name" . }}
  {{- if (.Values.networkPolicy.spec).policyTypes }}
  policyTypes:
  {{- toYaml .Values.networkPolicy.spec.policyTypes | nindent 4 }}
  {{- end }}
  {{- if (.Values.networkPolicy.spec).ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.spec.ingress | nindent 4 }}
  {{- end }}
  {{- if (.Values.networkPolicy.spec).egress }}
  egress:
    {{- toYaml .Values.networkPolicy.spec.egress | nindent 4 }}
  {{- end }}
{{- end }}
